### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by NicholasZehr** [NicholasZehr/athomeMVP#2]
##### Features
- [ ] Shows when User clicks Tasks
- [ ] Shows all tasks for that user.
- [ ] Shows their status. 
- [ ] Allows user to ‘Complete’ tasks.
